import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

const shared = {
    banner: { js: banner },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    target: "es2018",
    treeShaking: true,
    logLevel: "info"
};

// 🧱 Production build
const productionContext = await esbuild.context({
    ...shared,
    entryPoints: ["main.ts"],
    bundle: true,
    format: "cjs",
    minify: true,
    outdir: "dist",
    sourcemap: false
});

// 🎨 CSS bundle (unchanged)
const cssContext = await esbuild.context({
    ...shared,
    entryPoints: ["styles.css", "timeline table rows.css"],
    bundle: true,
    format: "esm",
    outdir: "dist",
    sourcemap: false
});

// 🧩 Debug/dev build (used by `npm run dev`)
const debugContext = await esbuild.context({
    ...shared,
    entryPoints: ["main.ts"],
    bundle: true,
    format: "cjs",
    outfile: "main.js",
    sourcemap: "inline",          // ✅ inline map so VS Code never loses it
    sourcesContent: true,         // ✅ embed original sources
    sourceRoot: "./",             // ✅ clarify that sources are relative to workspace root
    minify: false,
    absWorkingDir: process.cwd(), // <--- ensures relative sources

    // watch: true
});

if (prod) {
    await productionContext.rebuild().catch(() => process.exit(1));
    await cssContext.rebuild().catch(() => process.exit(1));

    fs.copyFile("manifest.json", "dist/manifest.json", (err) => {
        if (err) throw err;
        console.log("manifest.json copied to dist/");
    });
    process.exit(0);
} else {
    await debugContext.watch();
}
